server {
  listen 80;

  # Web UI në root
  location / {
    proxy_pass http://web:8080;
    proxy_set_header Host $host;
  }

  # Shlink API endpoints
  location /rest/ {
    proxy_pass http://shlink:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
